#!/usr/bin/env python
from misc.utility.scons_hints import *

Import('env')
Import("env_modules")

lib_env = env_modules.Clone()

sources = [
    "src/google/protobuf/arena.cc",
    "src/google/protobuf/arenastring.cc",
    "google/protobuf/any.cc"
    "google/protobuf/descriptor.cc"
    "google/protobuf/descriptor.pb.cc"
    "google/protobuf/dynamic_message.cc"
    "google/protobuf/internal_visibility.cc"
    "google/protobuf/io/coded_stream.cc"
    "google/protobuf/io/strtod.cc"
    "google/protobuf/io/tokenizer.cc"
    "google/protobuf/io/zero_copy_stream.cc"
    "google/protobuf/io/zero_copy_stream_impl_lite.cc"
    "google/protobuf/map_field.cc"
    "google/protobuf/message.cc"
    "google/protobuf/message_lite.cc"
    "google/protobuf/text_format.cc"
    "google/protobuf/reflection_mode.cc"
    "google/protobuf/repeated_field.cc"
    "google/protobuf/unknown_field_set.cc"
    "google/protobuf/parse_context.cc"

    # ... and so on for all required protobuf source files
]

lib_env.Append(CPPPATH=["src/"])

library = lib_env.StaticLibrary("#libprotobuf", sources)

env.Append(LIBS=[library])

env.Append(CPPPATH=["#src"])